# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('companylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 2, 26, 18, 44, 11, 369244, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
