# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 11:13
from __future__ import unicode_literals

import companylist.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('companylist', '0003_auto_20160301_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['parent__id']},
        ),
        migrations.AddField(
            model_name='parent',
            name='company_estimated_earnings',
            field=models.CharField(default=datetime.datetime(2016, 3, 1, 11, 13, 3, 541241, tzinfo=utc), max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='content',
            field=models.TextField(default=datetime.datetime(2016, 3, 1, 11, 13, 14, 320889, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parent',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=companylist.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='parent',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
