# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companylist', '0004_auto_20160301_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
